<#
.SYNOPSIS
Executes Adobe's RemoteUpdateManager.exe which will update creative cloud
applications on the machine.
.NOTES
Author:     Matt McPhee
Created:    06/05/2025
Updated:    06/05/2025
#>

function Write-Log {
    <#
    .SYNOPSIS
        This function will write a message to a file for logging purposes.
    .PARAMETER Message
        A message to be logged. Can accept an array of messages (each message will be logged on a separate line).
    .PARAMETER Level
        The severity level of the log line. Can be Info (default), Warn or Error.
    .PARAMETER Path
        The desired path the log will be written to. Must include filename and file extension.
    .OUTPUTS
        Appends a line to a log file.
    #>
    [CmdletBinding()]
    param(
        # Message
        [Parameter(Mandatory=$true,ValueFromPipeline)]
        [AllowEmptyString()]
        [AllowNull()]
        [string[]]
        $Message,
        # Level
        [Parameter(Mandatory=$false)]
        [ValidateSet("Error", "Warning", "Info")]
        [string]
        $Level = "Info",
        # Path
        [Parameter(Mandatory=$true)]
        [ValidateNotNullOrEmpty()]
        [string]
        $Path
    )

    process {
        # convert level to type codes so cmtrace can read it
        switch ($Level) {
            "Info" { [int]$Type = 1 }
            "Warning" { [int]$Type = 2 }
            "Error" { [int]$Type = 3 }
        }

        # create log entry
        $logLine = "<![LOG[$Message]LOG]!>" +
        "<" +
        "time=`"$(Get-Date -Format "HH:mm:ss.ffffff")`" " +
        "date=`"$(Get-Date -Format "M-d-yyyy")`" " +
        "type=`"$Type`" " +
        ">"

        # append line to log file
        $logLine | Out-File -FilePath $Path -Append -Force -Encoding utf8
    }
}

$rumPath = "C:\Program Files (x86)\Common Files\Adobe\OOBE_Enterprise\RemoteUpdateManager\RemoteUpdateManager.exe"
$logPath = "C:\Windows\Logs\Software\Update-AdobeApps.log"

try {
    # attempt to run RemoteUpdateManager.exe
    Start-Process -FilePath $rumPath -WindowStyle 'Hidden' -ErrorAction 'Stop'
    Write-Log -Message "RemoteUpdateManager.exe launched." -Level 'Info' -Path $logPath
} catch {
    Write-Log -Message "Encountered this error when attempting to launch RemoteUpdateManager.exe:" -Level 'Error' -Path $logPath
    Write-Log -Message "$_" -Level 'Error' -Path $logPath
}

# SIG # Begin signature block
# MIImfAYJKoZIhvcNAQcCoIImbTCCJmkCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCC/ftGPaLS82/jQ
# Kju+P8ecGlA9kHl4L0H59QucozHv06CCIIkwggWNMIIEdaADAgECAhAOmxiO+dAt
# 5+/bUOIIQBhaMA0GCSqGSIb3DQEBDAUAMGUxCzAJBgNVBAYTAlVTMRUwEwYDVQQK
# EwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5jb20xJDAiBgNV
# BAMTG0RpZ2lDZXJ0IEFzc3VyZWQgSUQgUm9vdCBDQTAeFw0yMjA4MDEwMDAwMDBa
# Fw0zMTExMDkyMzU5NTlaMGIxCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxEaWdpQ2Vy
# dCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5jb20xITAfBgNVBAMTGERpZ2lD
# ZXJ0IFRydXN0ZWQgUm9vdCBHNDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoC
# ggIBAL/mkHNo3rvkXUo8MCIwaTPswqclLskhPfKK2FnC4SmnPVirdprNrnsbhA3E
# MB/zG6Q4FutWxpdtHauyefLKEdLkX9YFPFIPUh/GnhWlfr6fqVcWWVVyr2iTcMKy
# unWZanMylNEQRBAu34LzB4TmdDttceItDBvuINXJIB1jKS3O7F5OyJP4IWGbNOsF
# xl7sWxq868nPzaw0QF+xembud8hIqGZXV59UWI4MK7dPpzDZVu7Ke13jrclPXuU1
# 5zHL2pNe3I6PgNq2kZhAkHnDeMe2scS1ahg4AxCN2NQ3pC4FfYj1gj4QkXCrVYJB
# MtfbBHMqbpEBfCFM1LyuGwN1XXhm2ToxRJozQL8I11pJpMLmqaBn3aQnvKFPObUR
# WBf3JFxGj2T3wWmIdph2PVldQnaHiZdpekjw4KISG2aadMreSx7nDmOu5tTvkpI6
# nj3cAORFJYm2mkQZK37AlLTSYW3rM9nF30sEAMx9HJXDj/chsrIRt7t/8tWMcCxB
# YKqxYxhElRp2Yn72gLD76GSmM9GJB+G9t+ZDpBi4pncB4Q+UDCEdslQpJYls5Q5S
# UUd0viastkF13nqsX40/ybzTQRESW+UQUOsxxcpyFiIJ33xMdT9j7CFfxCBRa2+x
# q4aLT8LWRV+dIPyhHsXAj6KxfgommfXkaS+YHS312amyHeUbAgMBAAGjggE6MIIB
# NjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTs1+OC0nFdZEzfLmc/57qYrhwP
# TzAfBgNVHSMEGDAWgBRF66Kv9JLLgjEtUYunpyGd823IDzAOBgNVHQ8BAf8EBAMC
# AYYweQYIKwYBBQUHAQEEbTBrMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdp
# Y2VydC5jb20wQwYIKwYBBQUHMAKGN2h0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNv
# bS9EaWdpQ2VydEFzc3VyZWRJRFJvb3RDQS5jcnQwRQYDVR0fBD4wPDA6oDigNoY0
# aHR0cDovL2NybDMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0QXNzdXJlZElEUm9vdENB
# LmNybDARBgNVHSAECjAIMAYGBFUdIAAwDQYJKoZIhvcNAQEMBQADggEBAHCgv0Nc
# Vec4X6CjdBs9thbX979XB72arKGHLOyFXqkauyL4hxppVCLtpIh3bb0aFPQTSnov
# Lbc47/T/gLn4offyct4kvFIDyE7QKt76LVbP+fT3rDB6mouyXtTP0UNEm0Mh65Zy
# oUi0mcudT6cGAxN3J0TU53/oWajwvy8LpunyNDzs9wPHh6jSTEAZNUZqaVSwuKFW
# juyk1T3osdz9HNj0d1pcVIxv76FQPfx2CWiEn2/K2yCNNWAcAgPLILCsWKAOQGPF
# mCLBsln1VWvPJ6tsds5vIy30fnFqI2si/xK4VC0nftg62fC2h5b9W9FcrBjDTZ9z
# twGpn1eqXijiuZQwggaSMIIEeqADAgECAhMgAAAFP2o7V3p+QZkSAAAAAAU/MA0G
# CSqGSIb3DQEBCwUAMFwxEjAQBgoJkiaJk/IsZAEZFgJhdTETMBEGCgmSJomT8ixk
# ARkWA2NvbTETMBEGCgmSJomT8ixkARkWA2JtZDEcMBoGA1UEAxMTQk1EIElzc3Vp
# bmcgQ0EgMSBHNDAeFw0yNTAyMDUwNTA4MDFaFw0yNjAyMDUwNTA4MDFaMIG3MRIw
# EAYKCZImiZPyLGQBGRYCYXUxEzARBgoJkiaJk/IsZAEZFgNjb20xEzARBgoJkiaJ
# k/IsZAEZFgNibWQxEjAQBgNVBAsTCUxvY2F0aW9uczERMA8GA1UECwwIYXVfdXNl
# cnMxDDAKBgNVBAsTA2JtZDEZMBcGA1UECxMQTGV2ZWwgMiAtIEFjY2VzczELMAkG
# A1UECxMCSVQxGjAYBgNVBAMTEU1hdHRoZXcgTWNQaGVlIFNVMIIBIjANBgkqhkiG
# 9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlxo1+Igvb/P/vUtTNEDlMcSPPA8jpKVYY4sV
# 3ANO2ZcoqfpaT0zIF2o19ADw5WskNO1DQS/fC+vVrNVKzOdKjtxQjIdIqoV5/vkH
# aOrDRuW4SRHCffBBBNIWcMdALzZe8PKMVBH4s1yKouJo1b0gusAyKJdWHSoohits
# /D+fF5iHMv6hDSHHdHEbiUKMyU+yNnZNoxx74sucvP3M7oT2hNcRJMd8TTUCTMwl
# 51XfI1bFnmxTwpT8x4tXQf1s6uCsilkj4aYQDHyx31VQ6xKLFFYxzoEZQ7SJLXhc
# zlJvJwNbE7KLMaPWcCOIyxYMo3FVniU1XMZy6Whoij29Wbp/ZQIDAQABo4IB7zCC
# AeswPAYJKwYBBAGCNxUHBC8wLQYlKwYBBAGCNxUIn7s/hPCFSPWNB4G5wyiG3u99
# gQqEr6s2hO+iDQIBZAIBBTATBgNVHSUEDDAKBggrBgEFBQcDAzALBgNVHQ8EBAMC
# B4AwDAYDVR0TAQH/BAIwADAbBgkrBgEEAYI3FQoEDjAMMAoGCCsGAQUFBwMDMB0G
# A1UdDgQWBBTL/Gz7y0iKRu1tP6OoHl0oJSzLhDAfBgNVHSMEGDAWgBTN0yUMxwnC
# tpXIbxeaoir2yfeRNjBKBgNVHR8EQzBBMD+gPaA7hjlodHRwOi8vcGtpLmJtZC5j
# b20uYXUvcGtpL0JNRCUyMElzc3VpbmclMjBDQSUyMDElMjBHNC5jcmwwVQYIKwYB
# BQUHAQEESTBHMEUGCCsGAQUFBzAChjlodHRwOi8vcGtpLmJtZC5jb20uYXUvcGtp
# L0JNRCUyMElzc3VpbmclMjBDQSUyMDElMjBHNC5jcnQwKwYDVR0RBCQwIqAgBgor
# BgEEAYI3FAIDoBIMEG1tLnN1QGJtZC5jb20uYXUwTgYJKwYBBAGCNxkCBEEwP6A9
# BgorBgEEAYI3GQIBoC8ELVMtMS01LTIxLTM2NDY4ODYzLTExMTEyMzk1NDUtMTIz
# MjgyODQzNi02NzQwMzANBgkqhkiG9w0BAQsFAAOCAgEAc6Bo/67gttoOw9tr4rvE
# g9Su2lapRUEfsoH/U8um8VATppoT8PweNsKiLDuDOTD8m1mAgX1NVv0Mj4d2wg9p
# a1sxgal7tjFpe8LuMW3XAseg5uTxIP6ligdeycs3BwI+EPWLk7o8hy0dUHVGIJaD
# PayMibYdtpAZmiRSpKjrmei4AbS73i6CBOxGITqrghngGuZ7E7xmNOKqyaWd0TrD
# Hxo3z/+nEuCksfiomInJJqhm27BMoXc9zVgyIlMa4KwO+AZXFJbOcrTqIwd9mmll
# HIG1ZLP2XzfB8RznoUZt9YPst6/34/qBqwNEXgcsJJnACj/b9lIslUZhWey5yoTo
# sZ7tpbl0FAxqlHXNANwA8q5AolWpeGLG3lVpL4wKr3B2XFgmj/wGezbcWOmm/q1u
# ByTleyaJmIxqTzOFEKVbX8dH49XC0/OLwQxUFXGMI2D3fuXHSZE73gQmIYlVbXOP
# S79L9DHJWNfqdWMAoBe1ItqX7hrOINBq2st8/foJizBGXmLxOAywMBjGADYLgZCz
# MEIgF6YvUIClcKomb3BN/UparCCFHb1Krq/V/WAjS2g7324TgxgvXDTMMxtgf1VZ
# Zhu3wiNIj4rjH1uu2xEHOxCnuoyHPKNUyI05pIhb6DyrYPpBhp2hA80+hQSarBKl
# Nf8SJYCA3Z/TALFISb+cLQcwggauMIIElqADAgECAhAHNje3JFR82Ees/ShmKl5b
# MA0GCSqGSIb3DQEBCwUAMGIxCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxEaWdpQ2Vy
# dCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5jb20xITAfBgNVBAMTGERpZ2lD
# ZXJ0IFRydXN0ZWQgUm9vdCBHNDAeFw0yMjAzMjMwMDAwMDBaFw0zNzAzMjIyMzU5
# NTlaMGMxCzAJBgNVBAYTAlVTMRcwFQYDVQQKEw5EaWdpQ2VydCwgSW5jLjE7MDkG
# A1UEAxMyRGlnaUNlcnQgVHJ1c3RlZCBHNCBSU0E0MDk2IFNIQTI1NiBUaW1lU3Rh
# bXBpbmcgQ0EwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDGhjUGSbPB
# PXJJUVXHJQPE8pE3qZdRodbSg9GeTKJtoLDMg/la9hGhRBVCX6SI82j6ffOciQt/
# nR+eDzMfUBMLJnOWbfhXqAJ9/UO0hNoR8XOxs+4rgISKIhjf69o9xBd/qxkrPkLc
# Z47qUT3w1lbU5ygt69OxtXXnHwZljZQp09nsad/ZkIdGAHvbREGJ3HxqV3rwN3mf
# XazL6IRktFLydkf3YYMZ3V+0VAshaG43IbtArF+y3kp9zvU5EmfvDqVjbOSmxR3N
# Ng1c1eYbqMFkdECnwHLFuk4fsbVYTXn+149zk6wsOeKlSNbwsDETqVcplicu9Yem
# j052FVUmcJgmf6AaRyBD40NjgHt1biclkJg6OBGz9vae5jtb7IHeIhTZgirHkr+g
# 3uM+onP65x9abJTyUpURK1h0QCirc0PO30qhHGs4xSnzyqqWc0Jon7ZGs506o9UD
# 4L/wojzKQtwYSH8UNM/STKvvmz3+DrhkKvp1KCRB7UK/BZxmSVJQ9FHzNklNiyDS
# LFc1eSuo80VgvCONWPfcYd6T/jnA+bIwpUzX6ZhKWD7TA4j+s4/TXkt2ElGTyYwM
# O1uKIqjBJgj5FBASA31fI7tk42PgpuE+9sJ0sj8eCXbsq11GdeJgo1gJASgADoRU
# 7s7pXcheMBK9Rp6103a50g5rmQzSM7TNsQIDAQABo4IBXTCCAVkwEgYDVR0TAQH/
# BAgwBgEB/wIBADAdBgNVHQ4EFgQUuhbZbU2FL3MpdpovdYxqII+eyG8wHwYDVR0j
# BBgwFoAU7NfjgtJxXWRM3y5nP+e6mK4cD08wDgYDVR0PAQH/BAQDAgGGMBMGA1Ud
# JQQMMAoGCCsGAQUFBwMIMHcGCCsGAQUFBwEBBGswaTAkBggrBgEFBQcwAYYYaHR0
# cDovL29jc3AuZGlnaWNlcnQuY29tMEEGCCsGAQUFBzAChjVodHRwOi8vY2FjZXJ0
# cy5kaWdpY2VydC5jb20vRGlnaUNlcnRUcnVzdGVkUm9vdEc0LmNydDBDBgNVHR8E
# PDA6MDigNqA0hjJodHRwOi8vY3JsMy5kaWdpY2VydC5jb20vRGlnaUNlcnRUcnVz
# dGVkUm9vdEc0LmNybDAgBgNVHSAEGTAXMAgGBmeBDAEEAjALBglghkgBhv1sBwEw
# DQYJKoZIhvcNAQELBQADggIBAH1ZjsCTtm+YqUQiAX5m1tghQuGwGC4QTRPPMFPO
# vxj7x1Bd4ksp+3CKDaopafxpwc8dB+k+YMjYC+VcW9dth/qEICU0MWfNthKWb8RQ
# TGIdDAiCqBa9qVbPFXONASIlzpVpP0d3+3J0FNf/q0+KLHqrhc1DX+1gtqpPkWae
# LJ7giqzl/Yy8ZCaHbJK9nXzQcAp876i8dU+6WvepELJd6f8oVInw1YpxdmXazPBy
# oyP6wCeCRK6ZJxurJB4mwbfeKuv2nrF5mYGjVoarCkXJ38SNoOeY+/umnXKvxMfB
# wWpx2cYTgAnEtp/Nh4cku0+jSbl3ZpHxcpzpSwJSpzd+k1OsOx0ISQ+UzTl63f8l
# Y5knLD0/a6fxZsNBzU+2QJshIUDQtxMkzdwdeDrknq3lNHGS1yZr5Dhzq6YBT70/
# O3itTK37xJV77QpfMzmHQXh6OOmc4d0j/R0o08f56PGYX/sr2H7yRp11LB4nLCbb
# bxV7HhmLNriT1ObyF5lZynDwN7+YAN8gFk8n+2BnFqFmut1VwDophrCYoCvtlUG3
# OtUVmDG0YgkPCr2B2RP+v6TR81fZvAT6gt4y3wSJ8ADNXcL50CN/AAvkdgIm2fBl
# dkKmKYcJRyvmfxqkhQ/8mJb2VVQrH4D6wPIOK+XW+6kvRBVK5xMOHds3OBqhK/bt
# 1nz8MIIGvDCCBKSgAwIBAgIQC65mvFq6f5WHxvnpBOMzBDANBgkqhkiG9w0BAQsF
# ADBjMQswCQYDVQQGEwJVUzEXMBUGA1UEChMORGlnaUNlcnQsIEluYy4xOzA5BgNV
# BAMTMkRpZ2lDZXJ0IFRydXN0ZWQgRzQgUlNBNDA5NiBTSEEyNTYgVGltZVN0YW1w
# aW5nIENBMB4XDTI0MDkyNjAwMDAwMFoXDTM1MTEyNTIzNTk1OVowQjELMAkGA1UE
# BhMCVVMxETAPBgNVBAoTCERpZ2lDZXJ0MSAwHgYDVQQDExdEaWdpQ2VydCBUaW1l
# c3RhbXAgMjAyNDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAL5qc5/2
# lSGrljC6W23mWaO16P2RHxjEiDtqmeOlwf0KMCBDEr4IxHRGd7+L660x5XltSVhh
# K64zi9CeC9B6lUdXM0s71EOcRe8+CEJp+3R2O8oo76EO7o5tLuslxdr9Qq82aKcp
# A9O//X6QE+AcaU/byaCagLD/GLoUb35SfWHh43rOH3bpLEx7pZ7avVnpUVmPvkxT
# 8c2a2yC0WMp8hMu60tZR0ChaV76Nhnj37DEYTX9ReNZ8hIOYe4jl7/r419CvEYVI
# rH6sN00yx49boUuumF9i2T8UuKGn9966fR5X6kgXj3o5WHhHVO+NBikDO0mlUh90
# 2wS/Eeh8F/UFaRp1z5SnROHwSJ+QQRZ1fisD8UTVDSupWJNstVkiqLq+ISTdEjJK
# GjVfIcsgA4l9cbk8Smlzddh4EfvFrpVNnes4c16Jidj5XiPVdsn5n10jxmGpxoMc
# 6iPkoaDhi6JjHd5ibfdp5uzIXp4P0wXkgNs+CO/CacBqU0R4k+8h6gYldp4FCMgr
# XdKWfM4N0u25OEAuEa3JyidxW48jwBqIJqImd93NRxvd1aepSeNeREXAu2xUDEW8
# aqzFQDYmr9ZONuc2MhTMizchNULpUEoA6Vva7b1XCB+1rxvbKmLqfY/M/SdV6mwW
# TyeVy5Z/JkvMFpnQy5wR14GJcv6dQ4aEKOX5AgMBAAGjggGLMIIBhzAOBgNVHQ8B
# Af8EBAMCB4AwDAYDVR0TAQH/BAIwADAWBgNVHSUBAf8EDDAKBggrBgEFBQcDCDAg
# BgNVHSAEGTAXMAgGBmeBDAEEAjALBglghkgBhv1sBwEwHwYDVR0jBBgwFoAUuhbZ
# bU2FL3MpdpovdYxqII+eyG8wHQYDVR0OBBYEFJ9XLAN3DigVkGalY17uT5IfdqBb
# MFoGA1UdHwRTMFEwT6BNoEuGSWh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9EaWdp
# Q2VydFRydXN0ZWRHNFJTQTQwOTZTSEEyNTZUaW1lU3RhbXBpbmdDQS5jcmwwgZAG
# CCsGAQUFBwEBBIGDMIGAMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2Vy
# dC5jb20wWAYIKwYBBQUHMAKGTGh0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9E
# aWdpQ2VydFRydXN0ZWRHNFJTQTQwOTZTSEEyNTZUaW1lU3RhbXBpbmdDQS5jcnQw
# DQYJKoZIhvcNAQELBQADggIBAD2tHh92mVvjOIQSR9lDkfYR25tOCB3RKE/P09x7
# gUsmXqt40ouRl3lj+8QioVYq3igpwrPvBmZdrlWBb0HvqT00nFSXgmUrDKNSQqGT
# dpjHsPy+LaalTW0qVjvUBhcHzBMutB6HzeledbDCzFzUy34VarPnvIWrqVogK0qM
# 8gJhh/+qDEAIdO/KkYesLyTVOoJ4eTq7gj9UFAL1UruJKlTnCVaM2UeUUW/8z3fv
# jxhN6hdT98Vr2FYlCS7Mbb4Hv5swO+aAXxWUm3WpByXtgVQxiBlTVYzqfLDbe9Pp
# BKDBfk+rabTFDZXoUke7zPgtd7/fvWTlCs30VAGEsshJmLbJ6ZbQ/xll/HjO9JbN
# VekBv2Tgem+mLptR7yIrpaidRJXrI+UzB6vAlk/8a1u7cIqV0yef4uaZFORNekUg
# QHTqddmsPCEIYQP7xGxZBIhdmm4bhYsVA6G2WgNFYagLDBzpmk9104WQzYuVNsxy
# oVLObhx3RugaEGru+SojW4dHPoWrUhftNpFC5H7QEY7MhKRyrBe7ucykW7eaCuWB
# sBb4HOKRFVDcrZgdwaSIqMDiCLg4D+TPVgKx2EgEdeoHNHT9l3ZDBD+XgbF+23/z
# BjeCtxz+dL/9NWR6P2eZRi7zcEO1xwcdcqJsyz/JceENc2Sg8h3KeFUCS7tpFk7C
# rDqkMIIG7DCCBNSgAwIBAgITNQAAAALQZkt+ZnXzywAAAAAAAjANBgkqhkiG9w0B
# AQsFADBXMRIwEAYKCZImiZPyLGQBGRYCYXUxEzARBgoJkiaJk/IsZAEZFgNjb20x
# EzARBgoJkiaJk/IsZAEZFgNibWQxFzAVBgNVBAMTDkJNRCBSb290IENBIEc0MB4X
# DTIzMDYxMTIzMDgyNFoXDTMzMDYxMTIzMTgyNFowXDESMBAGCgmSJomT8ixkARkW
# AmF1MRMwEQYKCZImiZPyLGQBGRYDY29tMRMwEQYKCZImiZPyLGQBGRYDYm1kMRww
# GgYDVQQDExNCTUQgSXNzdWluZyBDQSAxIEc0MIICIjANBgkqhkiG9w0BAQEFAAOC
# Ag8AMIICCgKCAgEAz8x/9sgDhYPEIfxgruf/qdWngrJq3rMif2LPSj8rZ+btT9Gy
# 9S+M+8E3sy2R7SzYqVE3QU7DOifIAJ6e0/NZf/iz4kKCgGBhOhw+z06OoN6u4q+K
# r7e0iLzoWHgEAi0Q8FqPvjFiIZdZLmY+e4+xmY2Zvp6aWzedaN2qeFVX2Ygq5cLy
# 22WwUyJAYW4vbUEC/hiLAcYjf0pxPvoAzvb9l/Zh8yaEk1v7hIvtKt3okHImeWDk
# 2frSRko0MB/xaIL3dww0d+q9RWMu2IIQ4+9vLUeYQCwjtxuakuMLdq83eRMGJXQe
# Cexo/S411LB/UsHpy8PdSX2CB4kCdQgV7+gtKiFm1DFDRhdbLBocC6tLxz8qUBok
# UFzVdP7Zc3OJvj0savWgK9tFQZwTnUMBGvwhzWFBccGf2HDYFLwIKxReZQWKgEo+
# frtSoAQ6OYiuwqWeujIg2c28SHLuy1PsmHFx11T1mWPItn0EtVxwAgAmTPLSG+BM
# LVyGtQcHGwKE0wN4nB0YDUQYwmzLp0Brp9MkxUBdK1qQDLI8tFGTXkdJnElAhzqM
# SurXTM/E5W7341x7qpXSt1EsawyK9u0fkuoSdyLxzkQtCVsfjFRstjSXnJ7memCe
# jpxCnQehik0xnZU91VGqMi7V3ChfDdcXAx4OxU28s9IDyX819Y43q4RE3aECAwEA
# AaOCAaowggGmMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBTN0yUMxwnCtpXI
# bxeaoir2yfeRNjCBgwYDVR0gBHwwejB4BggqAwSLL0NZBTBsMDoGCCsGAQUFBwIC
# MC4eLABMAGUAZwBhAGwAIABQAG8AbABpAGMAeQAgAFMAdABhAHQAZQBtAGUAbgB0
# MC4GCCsGAQUFBwIBFiJodHRwOi8vcGtpLmJtZC5jb20uYXUvcGtpL2Nwcy5odG1s
# MBkGCSsGAQQBgjcUAgQMHgoAUwB1AGIAQwBBMAsGA1UdDwQEAwIBhjAPBgNVHRMB
# Af8EBTADAQH/MB8GA1UdIwQYMBaAFPYnl2aA7inf9Q3I6drjUTr3ksg0MEMGA1Ud
# HwQ8MDowOKA2oDSGMmh0dHA6Ly9wa2kuYm1kLmNvbS5hdS9wa2kvQk1EJTIwUm9v
# dCUyMENBJTIwRzQuY3JsME4GCCsGAQUFBwEBBEIwQDA+BggrBgEFBQcwAoYyaHR0
# cDovL3BraS5ibWQuY29tLmF1L3BraS9CTUQlMjBSb290JTIwQ0ElMjBHNC5jcnQw
# DQYJKoZIhvcNAQELBQADggIBACLP3NoCk2HYRG2qqJurCda7Fyz19BWlaCG8eTov
# b3PxyTR42lGmq86vMY5cfDJVAFsN85qb4+CMXxhEGpwkXVywXX7oyWr4vFAbG10A
# +s0+Ow/5s3+Dffa+aG8TpsPdw/xQ0mRZWTgF1Nipu846nUJi/K0gXdEZVBXaguMK
# H0N5CzCsyR538NsQLjYILYwwm67R1VuZN0rBEPcC5ohFpDOYFuiYwMCik7TCdkkt
# OpfJQRyKO0GUsmXCD8CIiJ4GtNZtaRmje7ldAlVe5PEni8G9Tx4Lj4KN+W3hswCK
# vezUllVnNIXGe7Mv86DfBIwMoiLnYTv4ScQH7IRgLkkwALZsnst7rDW/xqLGxS4V
# IvILz6L5G5oXCVGKJpFlXwoVF8OzArf/Zd5tnTeB8oO72JsjZfM3P2qdFfhei9G3
# c7CJF0+gwRA3FvbvKMEY6NsoNYkMU2s5iLj8MO039EFD1Rc+oJ5FpefIoTt5OOXt
# 8t5vuT3BMIptYTrhi9MY05bE/EamtpcSvlb3qH1tH3P3K832i8APMrmzzDmwmMbO
# 0b5tA2K09uBk3XSRvbvWwa0DxbJ8jgJrkUtVOzBhC1Y7NqjsYixoRMUb4WEt932P
# dySlyiZaZ6NMC1y730PPHR7Lm+zEp2PFX4LTfukm+EjhGM4078bHsoSVuINSm78v
# DX2eMYIFSTCCBUUCAQEwczBcMRIwEAYKCZImiZPyLGQBGRYCYXUxEzARBgoJkiaJ
# k/IsZAEZFgNjb20xEzARBgoJkiaJk/IsZAEZFgNibWQxHDAaBgNVBAMTE0JNRCBJ
# c3N1aW5nIENBIDEgRzQCEyAAAAU/ajtXen5BmRIAAAAABT8wDQYJYIZIAWUDBAIB
# BQCggYQwGAYKKwYBBAGCNwIBDDEKMAigAoAAoQKAADAZBgkqhkiG9w0BCQMxDAYK
# KwYBBAGCNwIBBDAcBgorBgEEAYI3AgELMQ4wDAYKKwYBBAGCNwIBFTAvBgkqhkiG
# 9w0BCQQxIgQgFWrxm22SSSU1jhtAgpqZpl4UvPMMjxKr9Mo9hZaGRZAwDQYJKoZI
# hvcNAQEBBQAEggEAVJJBS6GTLmH3zgzWE6Nyn0SGNWEkHrRlhlCV84aft0wZMm/K
# uwTjGCV9RBMsnsitpC/TWl53msZkmwSq+9z/JIGq5Cx4YYPzdLUq9CgyirsFHZWn
# FasWsAiT6UCNzplSX73nC9hucdCotUZmQWgtKa0okjclykNQh+uxeFlktmQBmLJg
# E1RFlPI2vhqc827mJ2HHoNKvockxFRifhG6xvb4SGfiMpjuN9nDMXPzrvaaKSGYt
# BPWRBLVd93EqxT6uqA5diufnfkrqAnXYmB0bTggW2LBKDv8PfCg7tm/hB6hXF+Wk
# aMwyRxzYPd1pbYODJRj4MGLq0CrkwN5RrdwZuKGCAyAwggMcBgkqhkiG9w0BCQYx
# ggMNMIIDCQIBATB3MGMxCzAJBgNVBAYTAlVTMRcwFQYDVQQKEw5EaWdpQ2VydCwg
# SW5jLjE7MDkGA1UEAxMyRGlnaUNlcnQgVHJ1c3RlZCBHNCBSU0E0MDk2IFNIQTI1
# NiBUaW1lU3RhbXBpbmcgQ0ECEAuuZrxaun+Vh8b56QTjMwQwDQYJYIZIAWUDBAIB
# BQCgaTAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJBTEPFw0y
# NTA1MDYwMzM1NDlaMC8GCSqGSIb3DQEJBDEiBCCk48M9VcC7A1JozxLcepKiYAus
# Dr6QPJULKLH0rWLkEDANBgkqhkiG9w0BAQEFAASCAgA22OlHKQdRrqB8pAfFyXIK
# 4T2waog3/f3pwoCrxtt9lSzTurqC1iYFU/Jo3H9f+AX/wtgLylog9xMLbKctiCie
# 44qPAEhqzoQfkMaIMoW1X6gSslYx8bEIAJxnqrynbpWe/fxxhb4tiRBi7y+MSRHQ
# WpSkEIRE5osJJJjq4jMkWPKfot+6AoxqwFMqjp4IM8REaPovo8vv9FsfvsGFy+Pb
# 5vPGgieH51NnFa3xT+XgK85DKhwwh54cecT0iXCdq9xPVOjawmMXb6TwFgy8mjAv
# 1F3xh21M+a+fKKNPf/UxoNyXolaVjrQV+zI7dYG95907Unq8oiYu6Tbc7ucWDvPB
# OQWE6T/GzDhxe6aScVfmpFoQ6epCMnun91FBOI1/ni3GgTLYHVWfZYEve/Q/YCB0
# 9oXZwQiqJcacP1k0EhdeOJ6vY7ogb89gQcY5/xH9sVdGS02eq50ufbwtKdjiJGQj
# qTiU7ls5Wc2A+kdC0Gh1CdklqU0TWCma9xWMkDvZkum1Tv1WuE/8Iy6iU9YSOqaK
# PqW/xzgaf/hYtbQsMRshwpERghNkLnZF42q8nWaafN8heMIiADxOseJo3n9ZQbYy
# TQUWQJD+yCX2cEMJvnKDXVNUsTmVc4xe6CuNpKf4YPUNsAS23dXL50PxX/oK+ydN
# oOuShoECISYK6sOtTHVhhg==
# SIG # End signature block
